import {
  Type,
  BoxIcon as ButtonIcon,
  Layout,
  ImageIcon,
  Quote,
  Clock,
  TimerIcon as Timeline,
  MessageSquare,
  FootprintsIcon as Footer,
  Heart,
  Waves,
  Sparkles,
  PartyPopper,
  Video,
  Music,
  Grid3X3,
  LayoutGrid,
  CalendarDays,
} from "lucide-react";

export const componentLibrary = [
  {
    id: "text",
    name: "Text",
    category: "Basic",
    type: "text",
    description: "Add text content with formatting options",
    icon: <Type className="h-5 w-5 text-primary" />,
    data: {
      text: "Double click to edit this text",
      align: "left",
      size: "medium",
      color: "",
    },
  },
  {
    id: "image",
    name: "Image",
    category: "Basic",
    type: "image",
    description: "Display images with captions and styling",
    icon: <ImageIcon className="h-5 w-5 text-primary" />,
    data: {
      src: "/placeholder.svg?height=400&width=600&query=beautiful image",
      alt: "Image description",
      caption: "",
      width: "100%",
      height: "auto",
      rounded: true,
    },
  },
  {
    id: "button",
    name: "Button",
    category: "Basic",
    type: "button",
    description: "Interactive buttons with custom styling",
    icon: <ButtonIcon className="h-5 w-5 text-primary" />,
    data: {
      text: "Click me",
      url: "#",
      variant: "default",
      size: "default",
      align: "center",
    },
  },
  {
    id: "header",
    name: "Header",
    category: "Sections",
    type: "header",
    description: "Page headers with title and subtitle",
    icon: <Layout className="h-5 w-5 text-primary" />,
    data: {
      title: "Page Title",
      subtitle: "A brief description of this page",
      align: "center",
      showDivider: true,
    },
  },
  {
    id: "hero",
    name: "Hero",
    category: "Sections",
    type: "hero",
    description: "Eye-catching hero sections with background images",
    icon: <ImageIcon className="h-5 w-5 text-primary" />,
    data: {
      title: "Welcome to My Special Page",
      subtitle: "Created with love just for you",
      backgroundImage: "/placeholder.svg?height=600&width=1200&query=beautiful landscape with hearts",
      buttonText: "Learn More",
      buttonUrl: "#",
      overlay: true,
      height: 60,
      marginTop: 0,
      marginBottom: 0,
      marginLeft: 0,
      marginRight: 0,
      paddingTop: 0,
      paddingBottom: 0,
      paddingLeft: 0,
      paddingRight: 0,
      borderRadius: 0,
      textAlign: "center",
    },
  },
  {
    id: "gallery",
    name: "Gallery",
    category: "Sections",
    type: "gallery",
    description: "Photo galleries with customizable layouts",
    icon: <ImageIcon className="h-5 w-5 text-primary" />,
    data: {
      title: "Photo Gallery",
      images: [
        {
          src: "/placeholder.svg?height=400&width=600&query=happy couple",
          alt: "Image 1",
          caption: "Our first date",
        },
        {
          src: "/placeholder.svg?height=400&width=600&query=romantic dinner",
          alt: "Image 2",
          caption: "Anniversary dinner",
        },
        {
          src: "/placeholder.svg?height=400&width=600&query=beach vacation",
          alt: "Image 3",
          caption: "Summer vacation",
        },
      ],
      columns: 3,
      gap: "medium",
    },
  },
  {
    id: "quote",
    name: "Quote",
    category: "Content",
    type: "quote",
    description: "Beautiful quotes with author attribution",
    icon: <Quote className="h-5 w-5 text-primary" />,
    data: {
      text: "Love is not about how many days, months, or years you have been together. Love is about how much you love each other every single day.",
      author: "Anonymous",
      align: "center",
      style: "modern",
    },
  },
  {
    id: "countdown",
    name: "Countdown",
    category: "Interactive",
    type: "countdown",
    description: "Countdown timers for special events",
    icon: <Clock className="h-5 w-5 text-primary" />,
    data: {
      title: "Counting down to our special day",
      date: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
      showLabels: true,
      style: "cards",
    },
  },
  {
    id: "date-difference",
    name: "Tempo Decorrido",
    category: "Interactive",
    type: "date-difference",
    description: "Mostra quanto tempo passou desde uma data específica",
    icon: <CalendarDays className="h-5 w-5 text-primary" />,
    data: {
      title: "Juntos há",
      date: new Date(Date.now() - 365 * 24 * 60 * 60 * 1000).toISOString(), // 1 ano atrás
      showLabels: true,
      style: "romantic",
      displayUnits: ["years", "months", "days"],
      customMessage: "Cada momento ao seu lado é especial ❤️",
      showTotalDays: true,
    },
  },
  {
    id: "timeline",
    name: "Timeline",
    category: "Content",
    type: "timeline",
    description: "Timeline of events and milestones",
    icon: <Timeline className="h-5 w-5 text-primary" />,
    data: {
      title: "Our Journey Together",
      events: [
        {
          date: "January 15, 2020",
          title: "First Met",
          description: "We met at a coffee shop downtown",
          type: "event",
        },
        {
          date: "March 8, 2020",
          title: "First Date",
          description: "Dinner at that Italian restaurant",
          type: "memory",
        },
        {
          date: "December 24, 2020",
          title: "Engagement",
          description: "I proposed during Christmas Eve",
          type: "milestone",
        },
      ],
      style: "vertical",
      theme: "default",
    },
  },
  {
    id: "message",
    name: "Message",
    category: "Content",
    type: "message",
    description: "Personal messages with custom styling",
    icon: <MessageSquare className="h-5 w-5 text-primary" />,
    data: {
      title: "A Special Message",
      message:
        "I wanted to create this page to show you how much you mean to me. Every moment with you is special, and I cherish our time together. Thank you for being you!",
      signature: "With love, Your Name",
      style: "card",
    },
  },
  {
    id: "footer",
    name: "Footer",
    category: "Sections",
    type: "footer",
    description: "Page footers with social links",
    icon: <Footer className="h-5 w-5 text-primary" />,
    data: {
      text: "Created with ❤️ using Memorizu",
      showSocialLinks: true,
      socialLinks: [
        { platform: "instagram", url: "#" },
        { platform: "facebook", url: "#" },
        { platform: "twitter", url: "#" },
      ],
    },
  },
  {
    id: "falling-hearts",
    name: "Falling Hearts",
    category: "Effects",
    type: "falling-hearts",
    description: "Animated falling hearts or shapes",
    icon: <Heart className="h-5 w-5 text-primary" />,
    data: {
      count: 15,
      speed: 4,
      size: 24,
      color: "#ff69b4",
      shape: "heart",
      direction: "down",
      opacity: 0.8,
      duration: 5,
      enabled: false,
    },
  },
  {
    id: "floating-bubbles",
    name: "Floating Bubbles",
    category: "Effects",
    type: "floating-bubbles",
    description: "Gentle floating bubble animation",
    icon: <Waves className="h-5 w-5 text-primary" />,
    data: {
      count: 12,
      minSize: 20,
      maxSize: 60,
      color: "#87ceeb",
      speed: 8,
      opacity: 0.6,
      blur: true,
      enabled: false,
    },
  },
  {
    id: "sparkle-effect",
    name: "Sparkle Effect",
    category: "Effects",
    type: "sparkle-effect",
    description: "Magical sparkle animations",
    icon: <Sparkles className="h-5 w-5 text-primary" />,
    data: {
      count: 25,
      size: 8,
      color: "#ffd700",
      secondaryColor: "#ffffff",
      speed: 2,
      intensity: 6,
      pattern: "random",
      enabled: false,
    },
  },
  {
    id: "confetti",
    name: "Confetti",
    category: "Effects",
    type: "confetti",
    description: "Celebration confetti animation",
    icon: <PartyPopper className="h-5 w-5 text-primary" />,
    data: {
      count: 50,
      colors: ["#ff0000", "#00ff00", "#0000ff", "#ffff00", "#ff00ff", "#00ffff"],
      shapes: ["square", "circle", "triangle"],
      speed: 3,
      spread: 60,
      gravity: 1.5,
      trigger: "continuous",
      enabled: false,
    },
  },
  {
    id: "video",
    name: "Video",
    category: "Media",
    type: "video",
    description: "Embed YouTube videos with custom controls",
    icon: <Video className="h-5 w-5 text-primary" />,
    data: {
      url: "",
      title: "",
      autoplay: false,
      controls: true,
      muted: false,
      loop: false,
      width: "100%",
      height: "auto",
      aspectRatio: "16/9",
      align: "center",
    },
  },
  {
    id: "music",
    name: "Music",
    category: "Media",
    type: "music",
    description: "Add audio files, search free music, or Spotify embeds",
    icon: <Music className="h-5 w-5 text-primary" />,
    data: {
      type: "api",
      audioUrl: "",
      spotifyUrl: "",
      title: "",
      artist: "",
      autoplay: false,
      loop: false,
      controls: true,
      volume: 1,
      align: "center",
      showArtwork: true,
      backgroundColor: "#f8f9fa",
      isFixed: false,
      fixedPosition: "top-right",
      isMinimized: false,
      tracks: [],
      embedHeight: 352,
      embedTheme: "auto",
      showCoverArt: true,
      playerStyle: "modern",
      animatedBackground: false,
      glowEffects: false,
      size: "compact",
      width: 100,
      maxWidth: "lg",
      position: "static",
      margin: { top: 0, bottom: 0, left: 0, right: 0 },
      padding: { top: 0, bottom: 0, left: 0, right: 0 },
    },
  },
  {
    id: "carousel",
    name: "Image Carousel",
    category: "Media",
    type: "carousel",
    description: "Customizable image carousel with multiple layouts and effects",
    icon: <ImageIcon className="h-5 w-5 text-primary" />,
    data: {
      title: "Image Gallery",
      images: [],
      autoplay: false,
      autoplaySpeed: 3,
      showDots: true,
      showArrows: true,
      showCaptions: true,
      enableHover: true,
      hoverEffect: "zoom",
      layout: "memory-board",
      theme: "default",
      borderRadius: 12,
      spacing: 16,
      height: 400,
      transition: "slide",
      randomRotation: false,
      maxRotation: 15,
      enableShuffle: true,
      overlayColor: "#000000",
      overlayOpacity: 0.5,
      backgroundColor: "transparent",
      width: "100%",
      maxWidth: "lg",
      marginTop: 0,
      marginBottom: 0,
      marginLeft: 0,
      marginRight: 0,
      paddingTop: 24,
      paddingBottom: 24,
      paddingLeft: 24,
      paddingRight: 24,
      borderWidth: 0,
      borderColor: "#e5e7eb",
      borderStyle: "solid",
      shadowSize: "none",
      shadowColor: "#000000",
      gridColumns: 3,
      gridGap: 16,
      showImageNumbers: false,
      collageBackground: "transparent",
    },
  },
  {
    id: "grid-2-columns",
    name: "2 Columns Grid",
    category: "Layout",
    type: "grid",
    description: "Two-column grid layout for organizing components",
    icon: <LayoutGrid className="h-5 w-5 text-primary" />,
    data: {
      columns: 2,
      height: 400,
      gap: 16,
      padding: 16,
      backgroundColor: "transparent",
      borderRadius: 8,
      gridColumns: [
        { id: "column-0", components: [] },
        { id: "column-1", components: [] },
      ],
    },
  },
  {
    id: "grid-3-columns",
    name: "3 Columns Grid",
    category: "Layout",
    type: "grid",
    description: "Three-column grid layout for organizing components",
    icon: <Grid3X3 className="h-5 w-5 text-primary" />,
    data: {
      columns: 3,
      height: 400,
      gap: 16,
      padding: 16,
      backgroundColor: "transparent",
      borderRadius: 8,
      gridColumns: [
        { id: "column-0", components: [] },
        { id: "column-1", components: [] },
        { id: "column-2", components: [] },
      ],
    },
  },
];
