import {
  Type,
  BoxIcon as ButtonIcon,
  Layout,
  ImageIcon,
  Quote,
  Clock,
  TimerIcon as Timeline,
  MessageSquare,
  FootprintsIcon as Footer,
  Heart,
  Waves,
  Sparkles,
  PartyPopper,
  Video,
  Music,
  Grid3X3,
  LayoutGrid,
  CalendarDays,
} from "lucide-react";
import { builderTranslations } from "@/lib/translations/builder-translations";

type Language = "pt-BR" | "en";

const getTranslation = (key: string, language: Language): string => {
  // Map pt-BR to pt for compatibility with translations
  const langKey = language === "pt-BR" ? "pt" : language;
  const translations = builderTranslations[langKey as keyof typeof builderTranslations];
  return (translations?.[key as keyof typeof translations] as string) || key;
};

export const getComponentLibrary = (language: Language = "pt-BR") => [
  {
    id: "text",
    name: getTranslation("component.text.name", language),
    category: getTranslation("component.basic", language),
    type: "text",
    description: getTranslation("component.text.description", language),
    icon: <Type className="h-5 w-5 text-primary" />,
    data: {
      text: getTranslation("text.clickToEdit", language),
      align: "left",
      size: "medium",
      color: "",
    },
  },
  {
    id: "image",
    name: getTranslation("component.image.name", language),
    category: getTranslation("component.basic", language),
    type: "image",
    description: getTranslation("component.image.description", language),
    icon: <ImageIcon className="h-5 w-5 text-primary" />,
    data: {
      src: "/placeholder.svg?height=400&width=600&query=beautiful image",
      alt: "Image description",
      caption: "",
      width: "100%",
      height: "auto",
      rounded: true,
    },
  },
  {
    id: "button",
    name: getTranslation("component.button.name", language),
    category: getTranslation("component.basic", language),
    type: "button",
    description: getTranslation("component.button.description", language),
    icon: <ButtonIcon className="h-5 w-5 text-primary" />,
    data: {
      text: language === "pt-BR" ? "Clique aqui" : "Click me",
      url: "#",
      variant: "default",
      size: "default",
      align: "center",
    },
  },
  {
    id: "header",
    name: getTranslation("component.header.name", language),
    category: getTranslation("component.sections", language),
    type: "header",
    description: getTranslation("component.header.description", language),
    icon: <Layout className="h-5 w-5 text-primary" />,
    data: {
      title: "Page Title",
      subtitle: "A brief description of this page",
      align: "center",
      showDivider: true,
    },
  },
  {
    id: "hero",
    name: getTranslation("component.hero.name", language),
    category: getTranslation("component.sections", language),
    type: "hero",
    description: getTranslation("component.hero.description", language),
    icon: <ImageIcon className="h-5 w-5 text-primary" />,
    data: {
      title: "Welcome to My Special Page",
      subtitle: "Created with love just for you",
      backgroundImage: "/placeholder.svg?height=600&width=1200&query=beautiful landscape with hearts",
      buttonText: "Learn More",
      buttonUrl: "#",
      overlay: true,
      height: 60,
      marginTop: 0,
      marginBottom: 0,
      marginLeft: 0,
      marginRight: 0,
      paddingTop: 0,
      paddingBottom: 0,
      paddingLeft: 0,
      paddingRight: 0,
      borderRadius: 0,
      textAlign: "center",
    },
  },
  {
    id: "gallery",
    name: getTranslation("component.gallery.name", language),
    category: getTranslation("component.sections", language),
    type: "gallery",
    description: getTranslation("component.gallery.description", language),
    icon: <ImageIcon className="h-5 w-5 text-primary" />,
    data: {
      title: "Photo Gallery",
      images: [
        {
          src: "/placeholder.svg?height=400&width=600&query=happy couple",
          alt: "Image 1",
          caption: "Our first date",
        },
        {
          src: "/placeholder.svg?height=400&width=600&query=romantic dinner",
          alt: "Image 2",
          caption: "Anniversary dinner",
        },
        {
          src: "/placeholder.svg?height=400&width=600&query=beach vacation",
          alt: "Image 3",
          caption: "Summer vacation",
        },
      ],
      columns: 3,
      gap: "medium",
    },
  },
  {
    id: "quote",
    name: getTranslation("component.quote.name", language),
    category: getTranslation("component.content", language),
    type: "quote",
    description: getTranslation("component.quote.description", language),
    icon: <Quote className="h-5 w-5 text-primary" />,
    data: {
      text: "Love is not about how many days, months, or years you have been together. Love is about how much you love each other every single day.",
      author: "Anonymous",
      align: "center",
      style: "modern",
    },
  },
  {
    id: "countdown",
    name: getTranslation("component.countdown.name", language),
    category: getTranslation("component.interactive", language),
    type: "countdown",
    description: getTranslation("component.countdown.description", language),
    icon: <Clock className="h-5 w-5 text-primary" />,
    data: {
      title: "Counting down to our special day",
      date: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
      showLabels: true,
      style: "cards",
    },
  },
  {
    id: "date-difference",
    name: getTranslation("component.dateDifference.name", language),
    category: getTranslation("component.interactive", language),
    type: "date-difference",
    description: getTranslation("component.dateDifference.description", language),
    icon: <CalendarDays className="h-5 w-5 text-primary" />,
    data: {
      title: "Juntos há",
      date: new Date(Date.now() - 365 * 24 * 60 * 60 * 1000).toISOString(), // 1 ano atrás
      showLabels: true,
      style: "romantic",
      displayUnits: ["years", "months", "days"],
      customMessage: "Cada momento ao seu lado é especial ❤️",
      showTotalDays: true,
    },
  },
  {
    id: "timeline",
    name: getTranslation("component.timeline.name", language),
    category: getTranslation("component.content", language),
    type: "timeline",
    description: getTranslation("component.timeline.description", language),
    icon: <Timeline className="h-5 w-5 text-primary" />,
    data: {
      title: "Our Journey Together",
      events: [
        {
          date: "January 15, 2020",
          title: "First Met",
          description: "We met at a coffee shop downtown",
          type: "event",
        },
        {
          date: "March 8, 2020",
          title: "First Date",
          description: "Dinner at that Italian restaurant",
          type: "memory",
        },
        {
          date: "December 24, 2020",
          title: "Engagement",
          description: "I proposed during Christmas Eve",
          type: "milestone",
        },
      ],
      style: "vertical",
      theme: "default",
    },
  },
  {
    id: "message",
    name: getTranslation("component.message.name", language),
    category: getTranslation("component.content", language),
    type: "message",
    description: getTranslation("component.message.description", language),
    icon: <MessageSquare className="h-5 w-5 text-primary" />,
    data: {
      title: "A Special Message",
      message:
        "I wanted to create this page to show you how much you mean to me. Every moment with you is special, and I cherish our time together. Thank you for being you!",
      signature: "With love, Your Name",
      style: "card",
    },
  },
  {
    id: "footer",
    name: getTranslation("component.footer.name", language),
    category: getTranslation("component.sections", language),
    type: "footer",
    description: getTranslation("component.footer.description", language),
    icon: <Footer className="h-5 w-5 text-primary" />,
    data: {
      text: "Created with ❤️ using Memorizu",
      showSocialLinks: true,
      socialLinks: [
        { platform: "instagram", url: "#" },
        { platform: "facebook", url: "#" },
        { platform: "twitter", url: "#" },
      ],
    },
  },
  {
    id: "falling-hearts",
    name: getTranslation("component.fallingHearts.name", language),
    category: getTranslation("component.effects", language),
    type: "falling-hearts",
    description: getTranslation("component.fallingHearts.description", language),
    icon: <Heart className="h-5 w-5 text-primary" />,
    data: {
      count: 15,
      speed: 4,
      size: 24,
      color: "#ff69b4",
      shape: "heart",
      direction: "down",
      opacity: 0.8,
      duration: 5,
      enabled: false,
    },
  },
  {
    id: "floating-bubbles",
    name: getTranslation("component.floatingBubbles.name", language),
    category: getTranslation("component.effects", language),
    type: "floating-bubbles",
    description: getTranslation("component.floatingBubbles.description", language),
    icon: <Waves className="h-5 w-5 text-primary" />,
    data: {
      count: 12,
      minSize: 20,
      maxSize: 60,
      color: "#87ceeb",
      speed: 8,
      opacity: 0.6,
      blur: true,
      enabled: false,
    },
  },
  {
    id: "sparkle-effect",
    name: getTranslation("component.sparkleEffect.name", language),
    category: getTranslation("component.effects", language),
    type: "sparkle-effect",
    description: getTranslation("component.sparkleEffect.description", language),
    icon: <Sparkles className="h-5 w-5 text-primary" />,
    data: {
      count: 25,
      size: 8,
      color: "#ffd700",
      secondaryColor: "#ffffff",
      speed: 2,
      intensity: 6,
      pattern: "random",
      enabled: false,
    },
  },
  {
    id: "confetti",
    name: getTranslation("component.confetti.name", language),
    category: getTranslation("component.effects", language),
    type: "confetti",
    description: getTranslation("component.confetti.description", language),
    icon: <PartyPopper className="h-5 w-5 text-primary" />,
    data: {
      count: 50,
      colors: ["#ff0000", "#00ff00", "#0000ff", "#ffff00", "#ff00ff", "#00ffff"],
      shapes: ["square", "circle", "triangle"],
      speed: 3,
      spread: 60,
      gravity: 1.5,
      trigger: "continuous",
      enabled: false,
    },
  },
  {
    id: "video",
    name: getTranslation("component.video.name", language),
    category: getTranslation("component.media", language),
    type: "video",
    description: getTranslation("component.video.description", language),
    icon: <Video className="h-5 w-5 text-primary" />,
    data: {
      url: "",
      title: "",
      autoplay: false,
      controls: true,
      muted: false,
      loop: false,
      width: "100%",
      height: "auto",
      aspectRatio: "16/9",
      align: "center",
    },
  },
  {
    id: "music",
    name: getTranslation("component.music.name", language),
    category: getTranslation("component.media", language),
    type: "music",
    description: getTranslation("component.music.description", language),
    icon: <Music className="h-5 w-5 text-primary" />,
    data: {
      type: "api",
      audioUrl: "",
      spotifyUrl: "",
      title: "",
      artist: "",
      autoplay: false,
      loop: false,
      controls: true,
      volume: 1,
      align: "center",
      showArtwork: true,
      backgroundColor: "#f8f9fa",
      isFixed: false,
      fixedPosition: "top-right",
      isMinimized: false,
      tracks: [],
      embedHeight: 352,
      embedTheme: "auto",
      showCoverArt: true,
      playerStyle: "modern",
      animatedBackground: false,
      glowEffects: false,
      size: "compact",
      width: 100,
      maxWidth: "lg",
      position: "static",
      margin: { top: 0, bottom: 0, left: 0, right: 0 },
      padding: { top: 0, bottom: 0, left: 0, right: 0 },
    },
  },
  {
    id: "carousel",
    name: getTranslation("component.carousel.name", language),
    category: getTranslation("component.media", language),
    type: "carousel",
    description: getTranslation("component.carousel.description", language),
    icon: <ImageIcon className="h-5 w-5 text-primary" />,
    data: {
      title: "Image Gallery",
      images: [],
      autoplay: false,
      autoplaySpeed: 3,
      showDots: true,
      showArrows: true,
      showCaptions: true,
      enableHover: true,
      hoverEffect: "zoom",
      layout: "memory-board",
      theme: "default",
      borderRadius: 12,
      spacing: 16,
      height: 400,
      transition: "slide",
      randomRotation: false,
      maxRotation: 15,
      enableShuffle: true,
      overlayColor: "#000000",
      overlayOpacity: 0.5,
      backgroundColor: "transparent",
      width: "100%",
      maxWidth: "lg",
      marginTop: 0,
      marginBottom: 0,
      marginLeft: 0,
      marginRight: 0,
      paddingTop: 24,
      paddingBottom: 24,
      paddingLeft: 24,
      paddingRight: 24,
      borderWidth: 0,
      borderColor: "#e5e7eb",
      borderStyle: "solid",
      shadowSize: "none",
      shadowColor: "#000000",
      gridColumns: 3,
      gridGap: 16,
      showImageNumbers: false,
      collageBackground: "transparent",
    },
  },
  {
    id: "grid-2-columns",
    name: getTranslation("component.grid.name", language) + " 2 " + getTranslation("columns", language),
    category: getTranslation("component.layout", language),
    type: "grid",
    description: getTranslation("component.grid.description", language),
    icon: <LayoutGrid className="h-5 w-5 text-primary" />,
    data: {
      columns: 2,
      height: 400,
      gap: 16,
      padding: 16,
      backgroundColor: "transparent",
      borderRadius: 8,
      gridColumns: [
        { id: "column-0", components: [] },
        { id: "column-1", components: [] },
      ],
    },
  },
  {
    id: "grid-3-columns",
    name: getTranslation("component.grid.name", language) + " 3 " + getTranslation("columns", language),
    category: getTranslation("component.layout", language),
    type: "grid",
    description: getTranslation("component.grid.description", language),
    icon: <Grid3X3 className="h-5 w-5 text-primary" />,
    data: {
      columns: 3,
      height: 400,
      gap: 16,
      padding: 16,
      backgroundColor: "transparent",
      borderRadius: 8,
      gridColumns: [
        { id: "column-0", components: [] },
        { id: "column-1", components: [] },
        { id: "column-2", components: [] },
      ],
    },
  },
];
